# Vilken python version koden ska tolkas som
# "py311" för python 3.12

target-version = "py312"

# Maxlängd på kodrader 

line-length = 88

#Vilka regel-familjer som ska användas(E=pycodestyle, F=pyflakes)

select = ["E", "F"]

# Regler att ignorera (E501 = för låga rader)

ignore = ["E501"]

# Mappar som ruff ska ignorera vid linting

exclude = [".venv", "build","__pycache__ "]